"""empty message

Revision ID: 095f8458e4d3
Revises: 
Create Date: 2023-04-06 14:09:15.888788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095f8458e4d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('types', name='typesenum'), nullable=False),
    sa.Column('moves', sa.String(length=255), nullable=False),
    sa.Column('encounterRate', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('catchRate', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('captured', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.Column('updatedAt', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.create_table('pokemon__type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('happieness', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('pokemonId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.Column('updatedAt', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pokemonId'], ['Pokemons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Items')
    op.drop_table('pokemon__type')
    op.drop_table('Pokemons')
    # ### end Alembic commands ###
